### ISSUE TITLE
 A question from a novice.

### ISSUE THREAD

**Issue by manlenzzz** [yxli2123/LoftQ#20]
Hello, if I wish to validate your baseline, what should I do? I am a beginner, and I'm still not quite clear after reading the Quick Start guide.

**Comment by yxli2123** [comment]
Hi @manlenzzz, thanks for your interest of our work. 

The baseline in our paper is basically QLoRA. Please refer to their repo. If you want to validate our method, LoftQ, on GSM8K dataset, the simplest way is to run this command: https://github.com/yxli2123/LoftQ/blob/main/scripts/test_gsm8k.sh#L9. You may change the batch size according to your GPUs.

In addition, the Quick Start guide is for finetuning.

**Comment by manlenzzz** [comment]
Thank you very much for your response, thank you!
