### ISSUE TITLE
The issue of not being able to download the LoftQ model from huggingface even when using an VPN 

### ISSUE THREAD

**Issue by Rain-yj** [yxli2123/LoftQ#21]
C:\Users\41936>git clone https://huggingface.co/LoftQ/Llama-2-7b-hf-4bit-64rank
Cloning into 'Llama-2-7b-hf-4bit-64rank'...
fatal: unable to access 'https://huggingface.co/LoftQ/Llama-2-7b-hf-4bit-64rank/': Failed to connect to huggingface.co port 443 after 21077 ms: Couldn't connect to server

**Comment by yxli2123** [comment]
Hi @Rain-yj , thanks for your interest of our work. The link works for me now. Please contact your network administrator to deal with this issue.

An alternative way is to download the HuggingFace repo and set the `from_pretrained` to your local directory you just downloaded.
Here are the command to download. You can also find them on HuggingFace:

# Make sure you have git-lfs installed (https://git-lfs.com)
```sh
git lfs install```

```sh
git clone https://huggingface.co/LoftQ/Llama-2-7b-hf-4bit-64rank
```

# If you want to clone without large files - just their pointers
```sh
GIT_LFS_SKIP_SMUDGE=10 git clone https://huggingface.co/LoftQ/Llama-2-7b-hf-4bit-64rank
```

**Comment by yxli2123** [comment]
Hi @Rain-yj , thanks for your interest of our work. The link works for me now. Please contact your network administrator to deal with this issue.

An alternative way is to download the HuggingFace repo and set the `from_pretrained` to your local directory you just downloaded.
Here are the command to download. You can also find them on HuggingFace:


```sh
# Make sure you have git-lfs installed (https://git-lfs.com)
git lfs install

git clone https://huggingface.co/LoftQ/Llama-2-7b-hf-4bit-64rank

```
