### ISSUE TITLE
Reproduce reported LORA16bit result on GSM8K

### ISSUE THREAD

**Issue by callanwu** [yxli2123/LoftQ#9]
Hello,
Great work! I want to reproduce the reported LoRA(16bit) result(**36.9**) on GSM8K dataset in your paper. 
Could you provide the correct script or more detailed hyper-parameters? Thx a lot!

**Comment by yxli2123** [comment]
Hi @callanwu, please try https://github.com/yxli2123/LoftQ/blob/main/scripts/train_gsm8k.sh#L62

**Comment by callanwu** [comment]
Thx a lot～ I will try it！
